
export const footerData = [
    {
        title: "Corporate",
        links: [
            "Customer Service",
            "Accounts",
            "Awards",
            "Achievements",
            "Current Events",
            "Executive Committee",
            "Our Foundation",
            "Human Resources",
            "Media Management",
            "Mission & Vision",
            "Organizational Struture",
            "Scholarships",
            "Testmonials",
            "Our Milestones",
            "Industry News",
        ],
    },
    {
        title: "Policies",
        links: [
            "Warranties",
            "Return Policy",
            "Product Liability",
            "Promotions",
            "Confidentiality",
            "Sustainability",
            "Government Policy",
            "Corporate Social Responsibility",
            "Credit Application",
            "Terms & Conditions",
            "Security & Maintenance",
            "Non Disclosure Agreement",
            "Insurances",
            "Complaints",
            "Privacy Policy",
            "Patents"
        ],
    },
    {
        title: "Sales",
        links: [
            "Pricing",
            "Exports",
            "Videos",
            "Trade Shows",
            "Sales Team",
            "Library",
            "Locations",
            "On going projects",
            "Ineractive Catalogs",
            "Valueable sales tools",
            "Follow your Order",
            "Request a Delivery",
            "Request for quote",
            "Digital Marketing",
            "Logistics",
            "Webinars"
        ]
    },
    {
        title: "Products",
        links: [
            "Behive Grates",
            "Catch Basin Traps",
            "Cleanouts",
            "Curb Boxes",
            "Curb Inlets",
            "Frames & Covers",
            "Frames & Grates",
            "Manhole Covers",
            "Manhole Grates",
            "Paving Products",
            "Specialty Products",
            "Tree Grates",
            "Trench Grates",
            "Utility Casting",
            "Valve Boxes",
            "Water Works Products"
        ],
    },
    {
        title: "Engineering",
        links: [
            "Submittals",
            "Data Sheets",
            "Engineers & Architects",
            "Customization",
            "Design Team",
            "Certificates",
            "Specifications",
            "Standards",
            "Get Digital With USF",
            "IT Department",
            "Case Studies",
            "Design & Innovations",
            "Product Approvals",
            "Quality Control",
            "Show Drawings"
        ]
    }, {
        title: "Support & Services",
        links: [
            "Technical Support", 
            "Customer Support", 
            "Engineering Consultancy", 
            "After Sales Services", 
            "Installation Support", 
            "Custom Support", 
            "Live Solution", 
            "Chemical Testing", 
            "PHysical Testing", 
            "Manual Testing", 
            "Testing & Inspection", 
            "Material Analysis", 
            "Quality Control Process", 
            "Apporval & Certification"
        ]
    },
];