export const partnerData = {
    Associations: [
        "/images/partner/PRECAST ASSOCIATIONS/1.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/2.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/3.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/4.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/5.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/6.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/7.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/8.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/9.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/10.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/11.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/12.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/13.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/14.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/15.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/16.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/17.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/18.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/19.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/20.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/21.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/22.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/23.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/24.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/25.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/26.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/27.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/28.jpg",
        "/images/partner/PRECAST ASSOCIATIONS/29.jpg",
    ],
    "Ready Mix": [
        "/images/partner/ReadyMix/1.png",
        "/images/partner/ReadyMix/2.png",
        "/images/partner/ReadyMix/3.png",
        "/images/partner/ReadyMix/4.png",
        "/images/partner/ReadyMix/5.png",
        "/images/partner/ReadyMix/6.png",
        "/images/partner/ReadyMix/7.png",
        "/images/partner/ReadyMix/8.png",
        "/images/partner/ReadyMix/9.png",
        "/images/partner/ReadyMix/10.png",
        "/images/partner/ReadyMix/11.png",
        "/images/partner/ReadyMix/12.png",
        "/images/partner/ReadyMix/13.png",
        "/images/partner/ReadyMix/14.png",
        "/images/partner/ReadyMix/15.png",
        "/images/partner/ReadyMix/16.png",
        "/images/partner/ReadyMix/17.png",
        "/images/partner/ReadyMix/18.png",
        "/images/partner/ReadyMix/19.png",
        "/images/partner/ReadyMix/20.png",
        "/images/partner/ReadyMix/21.png",
        "/images/partner/ReadyMix/22.png",
        "/images/partner/ReadyMix/23.png",
        "/images/partner/ReadyMix/24.png",
        "/images/partner/ReadyMix/25.png",
        "/images/partner/ReadyMix/26.png",
        "/images/partner/ReadyMix/27.png",
        "/images/partner/ReadyMix/28.png",
        "/images/partner/ReadyMix/29.png",
        "/images/partner/ReadyMix/30.png",
        "/images/partner/ReadyMix/31.png",
        "/images/partner/ReadyMix/32.png",
        "/images/partner/ReadyMix/33.png",
        "/images/partner/ReadyMix/34.png",
        "/images/partner/ReadyMix/35.png",
        "/images/partner/ReadyMix/36.png",
        "/images/partner/ReadyMix/37.png",
        "/images/partner/ReadyMix/38.png",
        "/images/partner/ReadyMix/39.png",
        "/images/partner/ReadyMix/40.png",
        "/images/partner/ReadyMix/41.png",
        "/images/partner/ReadyMix/42.png",
        "/images/partner/ReadyMix/43.png",
        "/images/partner/ReadyMix/44.png",
        "/images/partner/ReadyMix/45.png",
    ],
    Standards: [
        "/images/partner/standards/1.png",
        "/images/partner/standards/2.png",
        "/images/partner/standards/3.png",
        "/images/partner/standards/4.png",
        "/images/partner/standards/5.png",
        "/images/partner/standards/6.png",
        "/images/partner/standards/7.png",
        "/images/partner/standards/8.png",
        "/images/partner/standards/9.png",
        "/images/partner/standards/10.png",
        "/images/partner/standards/11.png",
        "/images/partner/standards/12.png",
        "/images/partner/standards/13.png",
    ],
    Accreditation: [
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
        "/PX/Low dome/Render images/12 FT LOW DOME.458.png",
    ]
};
